name: 03 Parallel jobs

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  linting:
    runs-on: ubuntu-latest # The runner environment (Ubuntu in this case)
    steps:
      - name: Linting 
        run: echo "Running linting..."

  unit_tests:
    runs-on: ubuntu-latest # The runner environment (Ubuntu in this case)
    steps:
      - name: Unit Tests
        run: echo "Running unit tests..."
    
  integration_tests:
    runs-on: ubuntu-latest # The runner environment (Ubuntu in this case)
    steps:
      - name: Set Up Test Environment
        run: echo "Setting up test environment..."

      - name: Integration Tests
        run: echo "Running integration tests..."
    