name: 07 Passing Files In Artifacts

on:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Python 3.10
        uses: actions/setup-python@v6 
        with:
          python-version: '3.10' 
      
      - name: Install tox
        run: pip install tox
      
      - name: Run unit test
        run: |
          cd backend
          tox -e unit
          ls -la ${{ github.workspace }}/backend/                            

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/backend/.coverage

  load-file-example:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage 
          path: ${{ github.workspace }}

      - name: List folder
        run: ls -la ${{ github.workspace }}
